openapi: 3.0.0
info:
  title: Copilot Hack Host API
  version: 1.0.0
paths:
  /api/factory:
    post:
      summary: Create a new factory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Factory'
      responses:
        '200':
          description: Factory created successfully
        '400':
          description: Invalid request body
        '500':
          description: Internal server error
components:
  schemas:
    Factory:
      type: object
      properties:
        name:
          type: string
        location:
          type: string
        machines:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              status:
                type: string